### ISSUE TITLE
UI needs improvement...

### ISSUE THREAD

**Issue by geremachek** [vllur/calc#1]
I recommend creating a kind of syntax for your calculator. instead of typing ```add``` and then having to type 2 numbers, do something like ```1 1 +``` and then it returns your answer. you could also do ```1 + 1```, but the first one is easier to implement. I did this in c++ with my calculator abacus. also check out ```dc```
and ```bc``` in linux.

**Comment by vllur** [comment]
Hi,
I'm afraid I'd have to replan whole app to do this, but I'll think of it. For now I'll close the issue, reopen it if you would want to add something.
Thanks for response!
